using UnityEngine;

namespace ByteWar.Core
{
    /// <summary>
    /// Centralizes game-wide constants that were previously scattered as magic numbers.
    /// Generated by AssetGenerator. Referenced at runtime via Resources.Load.
    /// </summary>
    [CreateAssetMenu(fileName = "GameConstants", menuName = "ByteWar/GameConstants")]
    public class GameConstants : ScriptableObject
    {
        [Header("Player Movement")]
        [SerializeField] private float _moveSpeed = 6f;
        [SerializeField] private float _turnSpeed = 14f;
        [SerializeField] private float _gravity = -18f;
        [SerializeField] private float _jumpForce = 6f;

        [Header("Combat")]
        [SerializeField] private float _meleeDamage = 10f;
        [SerializeField] private float _gatherDamage = 10f;
        [SerializeField] private float _fireballFallbackDamage = 25f;
        [SerializeField] private float _interactionRange = 100f;

        [Header("Application")]
        [SerializeField] private int _targetFrameRate = 60;

        // ── Read-only accessors ───────────────────────────────────────────────
        public float MoveSpeed => _moveSpeed;
        public float TurnSpeed => _turnSpeed;
        public float Gravity => _gravity;
        public float JumpForce => _jumpForce;
        public float MeleeDamage => _meleeDamage;
        public float GatherDamage => _gatherDamage;
        public float FireballFallbackDamage => _fireballFallbackDamage;
        public float InteractionRange => _interactionRange;
        public int TargetFrameRate => _targetFrameRate;

        // ── Runtime singleton accessor ────────────────────────────────────────
        private static GameConstants _instance;

        public static GameConstants Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = Resources.Load<GameConstants>("GameConstants");
                    if (_instance == null)
                        Debug.LogWarning("[GameConstants] GameConstants asset not found in Resources/. Using defaults.");
                }
                return _instance;
            }
        }

        /// <summary>Returns the value, or a fallback default if the asset is missing.</summary>
        public static float GetMoveSpeed() => Instance != null ? Instance.MoveSpeed : 6f;
        public static float GetTurnSpeed() => Instance != null ? Instance.TurnSpeed : 14f;
        public static float GetGravity() => Instance != null ? Instance.Gravity : -18f;
        public static float GetJumpForce() => Instance != null ? Instance.JumpForce : 6f;
        public static float GetMeleeDamage() => Instance != null ? Instance.MeleeDamage : 10f;
        public static float GetGatherDamage() => Instance != null ? Instance.GatherDamage : 10f;
        public static float GetFireballFallbackDamage() => Instance != null ? Instance.FireballFallbackDamage : 25f;
        public static float GetInteractionRange() => Instance != null ? Instance.InteractionRange : 100f;
        public static int GetTargetFrameRate() => Instance != null ? Instance.TargetFrameRate : 60;
    }
}
